import { NextApiRequest, NextApiResponse } from "next";
import Head from "next/head";
import CreatePost from "../components/createPost/CreatePost";
import PostCard from "../components/postCard/PostCard";
import commonStyles from "../styles/Common.module.css";
import connectToMongoDb from "../lib/mongodb";
import { cursorToDoc } from "../helpers/cursorToDoc";
import {
  PaginationData,
  Post,
  PostCategories,
  PostSortingOptions,
  UserAuthStatus,
} from "../interfaces/Common.interface";
import { useDispatch, useSelector } from "react-redux";
import { useEffect, useRef, useState } from "react";
import { append, refresh } from "../features/postSlice";
import { RootState } from "../store";
import { getPosts } from "../services/postServices";
import HomePageNavbar from "../components/homePageNavbar/HomePageNavbar";
import HomePageSidebar from "../components/homePageSidebar/HomePageSidebar";
import useInMobileView from "../hooks/useInMobileView";
import useIntersectionObserver from "../hooks/useIntersectionObserver";
import { MoonLoader } from "react-spinners";

export default function Home() {
  const posts = useSelector((state: RootState) => state.postSlice);
  const { status } = useSelector((state: RootState) => state.userSlice);
  const dispatch = useDispatch();
  const [sortedBy, setSortedBy] = useState<PostSortingOptions>(
    PostSortingOptions.DATE
  );
  const [filterBy, setFilterBy] = useState<PostCategories | null>(null);
  const { inMobileView } = useInMobileView();
  const [paginationData, setPaginationData] = useState<{
    count?: number;
    currentPage: number;
    nextPage: number | null;
    previousPage: number | null;
  }>({
    currentPage: 1,
    nextPage: null,
    previousPage: null,
  });
  const lastPostRef = useRef<HTMLDivElement | null>(null);
  const entry = useIntersectionObserver(lastPostRef, {});
  const [isFetchingPosts, setIsFetchingPosts] = useState<boolean>(false);

  useEffect(() => {
    if (entry && entry.isIntersecting) {
      if (paginationData.nextPage) {
        setPaginationData((prev) => ({
          ...prev,
          currentPage: prev.currentPage + 1,
        }));
      }
    }
  }, [entry?.isIntersecting]);

  useEffect(() => {
    const filter: PostCategories | undefined = filterBy ? filterBy : undefined;
    getPosts(
      sortedBy,
      paginationData.currentPage,
      filter,
      undefined,
      undefined,
      setIsFetchingPosts,
      (result) => {
        dispatch(refresh({ newPosts: result.data.data.posts }));
        if (result.data.data.paginationData) {
          setPaginationData(result.data.data.paginationData);
        }
      }
    );
  }, []);

  useEffect(() => {
    if (paginationData.currentPage === 1) return;
    const filter: PostCategories | undefined = filterBy ? filterBy : undefined;
    getPosts(
      sortedBy,
      paginationData.currentPage,
      filter,
      undefined,
      undefined,
      setIsFetchingPosts,
      (result) => {
        dispatch(append({ newPosts: result.data.data.posts }));
        if (result.data.data.paginationData) {
          setPaginationData(result.data.data.paginationData);
        }
      }
    );
  }, [paginationData.currentPage]);

  useEffect(() => {
    const filter: PostCategories | undefined = filterBy ? filterBy : undefined;
    getPosts(
      sortedBy,
      1,
      filter,
      undefined,
      undefined,
      setIsFetchingPosts,
      (result) => {
        dispatch(refresh({ newPosts: result.data.data.posts }));
        if (result.data.data.paginationData) {
          setPaginationData(paginationData);
        }
      }
    );
  }, [sortedBy, filterBy]);

  return (
    <>
      <Head>
        <title>Dev Net</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <>
        {inMobileView === false && <HomePageSidebar />}
        <div className={commonStyles.pagePostsSection}>
          {status === UserAuthStatus.AUTHENTICATED && <CreatePost />}
          <div className={commonStyles.chipContainer}>
            <label
              className={`${commonStyles.chip} ${
                sortedBy === PostSortingOptions.DATE
                  ? commonStyles.chipActive
                  : ""
              }`}
            >
              <input
                defaultChecked
                type="checkbox"
                name="post-sort-by"
                onChange={() => setSortedBy(PostSortingOptions.DATE)}
              />
              date
            </label>

            <label
              className={`${commonStyles.chip} ${
                sortedBy === PostSortingOptions.TRENDING
                  ? commonStyles.chipActive
                  : ""
              }`}
            >
              <input
                type="checkbox"
                name="post-sort-by"
                onChange={() => setSortedBy(PostSortingOptions.TRENDING)}
              />
              trending
            </label>

            <label
              className={`${commonStyles.chip} ${
                filterBy === null ? commonStyles.chipActive : ""
              }`}
            >
              <input
                type="checkbox"
                name="post-filter-by"
                onChange={() => setFilterBy(null)}
              />
              all
            </label>
            <label
              className={`${commonStyles.chip} ${
                filterBy === PostCategories.GENERAL
                  ? commonStyles.chipActive
                  : ""
              }`}
            >
              <input
                type="checkbox"
                name="post-filter-by"
                onChange={() => setFilterBy(PostCategories.GENERAL)}
              />
              {PostCategories.GENERAL}
            </label>
            <label
              className={`${commonStyles.chip} ${
                filterBy === PostCategories.QUERY ? commonStyles.chipActive : ""
              }`}
            >
              <input
                type="checkbox"
                name="post-filter-by"
                onChange={() => setFilterBy(PostCategories.QUERY)}
              />
              {PostCategories.QUERY}
            </label>
          </div>
          <div className={commonStyles.postsContainer}>
            {posts.map((post, index) => (
              <PostCard
                lastPostRef={index === posts.length - 1 ? lastPostRef : null}
                key={post._id}
                details={post}
              />
            ))}
            {(isFetchingPosts || paginationData.nextPage === null) && (
              <div className={commonStyles.postsEndDataContainer}>
                {isFetchingPosts ? (
                  <MoonLoader size={30} />
                ) : (
                  <p>You have reached the end.</p>
                )}
              </div>
            )}
          </div>
        </div>
        <HomePageNavbar />
      </>
    </>
  );
}
